### ISSUE TITLE
Create/update multiple fleets over "configuration as code"

### ISSUE THREAD

**Issue by alb777** [jenkinsci/ec2-fleet-plugin#313]
Is it possible create more than one ec2fleet template configuration over the groovy script like this:

```yaml
jenkins:
  clouds:
    - ec2Fleet:
        name: ec2-fleet1
        computerConnector:
            ssh:
                credentialsId: cred1
                sshHostKeyVerificationStrategy:
                  NonVerifyingKeyVerificationStrategy
        region: us-east-2
        fleet: my-fleet1
        minSize: 1
        maxSize: 10
```

```yaml
jenkins:
  clouds:
    - ec2Fleet:
        name: ec2-fleet2
        computerConnector:
            ssh:
                credentialsId: cred2
                sshHostKeyVerificationStrategy:
                  NonVerifyingKeyVerificationStrategy
        region: us-east-2
        fleet: my-fleet2
        minSize: 2
        maxSize: 5
```

Besides that, if I wanna change the spot fleet request ID of a current template for example, is it possible through automation running the same groovy script with required modifications and  not by hand at Jenkins Fleet plugin console ?

**Comment by haugenj** [comment]
Yes, I haven't tested it but I believe you should be able to manage multiple fleets via the configuration as code plugin. I think the second fleet would be another entry under `clouds` such as
```
jenkins:
  clouds:
    - ec2Fleet:
        name: ec2-fleet1
        ...
    - ec2Fleet:
        name: ec2-fleet-2
```

And yes, you can update the fleet ID in the CasC and it should be ok. Some people have had issues with instances not getting terminated when doing this, but we addressed this in a recent release.
