### ISSUE TITLE
Support for instance weight when InstanceRequirements are used (not just InstanceType)

### ISSUE THREAD

**Issue by pbudzon** [jenkinsci/ec2-fleet-plugin#315]
**Is your feature request related to a problem? Please describe.**
We use spot fleet with `InstanceRequirements` set in LaunchSpecifications, instead of listing instance types. This allows for more flexible spot fleet - we specify requirements for the instances (min/max vcpus, memory, architecture) and spot fleet automatically chooses cheapest available instance type that matches those requirements (AWS docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-attribute-based-instance-type-selection.html).

This means we can get very different instances from the spot fleet: from t3.large to c5.24xlarge - which obviously vary very much in terms of resources. Currently the plugin will apply the same number of executors to each of those.

**Describe the solution you'd like**
It would be great, if number of executors could be dynamically adjusted, for example based on vcpus or memory on the instance. Ideally there would be a setting which would let the user choose how the number of executors should be calculated. I think to start with two strategies would fit most use-cases: 
1. number of executors = number of vcpus / user-provided divider (for example, 1 executor for each 2 cpus)
2. number of executors = memory GB / user-provided divider (for example, 1 executor for each 2GB of memory).

**Describe alternatives you've considered**
Our current setup simply goes with default 2 executors for every instance. We could specify a list of instance types, but based on AWS Console there's currently 119 instance types that match our specification, so that's not feasible.

**Additional context**
Spot fleet CloudFormation Template that we use:
```
SpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: lowestPrice
        ExcessCapacityTerminationPolicy: noTermination
        IamFleetRole: arn:aws:iam::xxx:role/xxx
        InstanceInterruptionBehavior: terminate
        LaunchSpecifications:
          - IamInstanceProfile:
              Arn: arn:aws:iam::xxx:instance-profile/ixxx
            ImageId: ami-xxxx
            InstanceRequirements:
              AcceleratorCount:
                Max: 0
              BurstablePerformance: included
              InstanceGenerations:
                - current
                - previous
              LocalStorage: included
              MemoryMiB:
                Min: 8192 # 8GB
              MemoryGiBPerVCpu:
                Min: 2
              RequireHibernateSupport: false
              VCpuCount:
                Min: 2
                Max: 8
            KeyName: xxx
            Monitoring:
              Enabled: false
            SecurityGroups:
              - GroupId: xxxx
            SubnetId: subnet-xxx,subnet-xxx
        OnDemandAllocationStrategy: lowestPrice
        OnDemandTargetCapacity: 0
        ReplaceUnhealthyInstances: true
        TargetCapacity: 0
        TargetCapacityUnitType: units
        TerminateInstancesWithExpiration: no
        Type: maintain
```

Side note:
Based on this, the plugin could also make smart changes to target capacity of the spot fleet, if `TargetCapacityUnitType` is set to `vcpu` for example to scale faster - but that's less important.
