### ISSUE TITLE
Plenty of workers suspended for several days.

### ISSUE THREAD

**Issue by mwos-sl** [jenkinsci/ec2-fleet-plugin#331]
## Issue Details
Not sure if related to: https://github.com/jenkinsci/ec2-fleet-plugin/issues/322, thus creating a separate issue.
Recently we noticed a very long jobs queue on jenkins. It turned out all ec2 fleets were maxed, but plenty of instances were in "suspended" and not disconnected from jenkins. EC2 instances themselves were fine on aws side. 
Even when I killed suspended instances using script, the new ones did some work but some of them eventually became suspended after some time too. IDLE time was not respected for those (we've got idle timeout configured to 3 minutes, some instances were connected for several days). 

**Describe the bug**
Example observation:
A lot of builds waiting for the an agent:
![image](https://user-images.githubusercontent.com/55095506/162787932-8856e22c-6088-4936-b272-01c5f56e8407.png)

And we can see that maximum number of agents for this label is already online:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/55095506/162788338-81898de1-dbcf-40b0-9805-17df379505da.png">

Still I see a lot of workers empty - with no job assisgned.
I see some of them with (suspended) text - in the view below all with red cross (screenshot from: `https://<jenkins url>/computer/`):

![image](https://user-images.githubusercontent.com/55095506/162788527-3e4dad5c-463c-424f-844a-c68edafaf3ec.png)

Vast majority of nodes with red-cross meaning "suspended".
One of those instances:
![image](https://user-images.githubusercontent.com/55095506/162788674-5f5001a0-acf1-4521-8ee9-0dabc58ec33e.png)

So this one was alive for several hours and it hasn't even built a single job. Yet plenty of jobs are waiting tens of minutes for this label to become available.

At this point we had to turn off `ec2-fleet-plugin` plugin and go back to `ec2-plugin`.
After we switched all the work to workers managed by `ec2-plugin`, the situation stabilised. 
However we would love to go back to using this plugin (`ec2-fleet-plugin`), because it's better with handling spot workers and using multi-instance-type. 

**To Reproduce**
I don't know. It just happened for all of our labels using this plugin.

## Environment Details

**Plugin Version?**
2.5.0

**Jenkins Version?**
2.336

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
```
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: true
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "standard-runner-ubuntu-user-private-key"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: "source /usr/bin/init-script.sh; "
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "build-jenkins-executor-sumo-agr-spot"
      fsRoot: "/mnt/jenkins/workspaces"
      idleMinutes: 3
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "sumo build agr spot 1executors"
      maxSize: 110
      maxTotalUses: 50
      minSize: 0
      minSpareSize: 0
      name: "build-jenkins-fleet-sumo-agr-spot"
      noDelayProvision: true
      numExecutors: 1
      oldId: "2fda8ebd-f7e6-4211-91c8-219c7ed8ceb6"
      privateIpUsed: true
      region: "us-west-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
```
Is this config OK?

**Anything else unique about your setup?**
Not sure if it's important, but our ASGs have:
```
protect_from_scale_in     = true
```
