### ISSUE TITLE
EC2 Fleet plugin JCasC can cause Jenkins startup to fail

### ISSUE THREAD

**Issue by peanderson2016** [jenkinsci/ec2-fleet-plugin#334]
## Issue Details

**Describe the bug**
When configuring the EC2 Fleet plugin via JCasC, if the credentials do not already exist or they are not valid, the plugin will cause Jenkins startup to fail. 

**To Reproduce**
1. Start from a clean Jenkins server
2. Create a JCasC file with credentials and EC2 Fleet plugin configuration
3. Start Jenkins 

1. Invalidate your EC2 Fleet credentials 
2. restart Jenkins

## Environment Details

**Plugin Version**
- ec2-fleet: 2.5.1

**Jenkins Version?**
- Jenkins: 2.303.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Windows

**EC2Fleet Configuration as Code**
``
credentials:
  system:
    domainCredentials:
    - credentials:
      - aws:
          accessKey: "MY_ACCESS_KEY"
          description: "AWS credentials"
          id: "aws-fleet-cred"
          scope: GLOBAL
          secretKey: "{MY_SECRET_KEY}"
jenkins:
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: true
      awsCredentialsId: "aws-fleet-cred"
      cloudStatusIntervalSec: 10
      computerConnector:
        managedWindowsServiceConnector:
          password: "{CONNECTOR_PASSWORD}"
          userName: "aws-fleet-user"
      credentialsId: "aws-fleet-cred"
      disableTaskResubmit: false
      fleet: "jenkins_ec2_win_code_builder"
      fsRoot: "C:\\worker_root"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "code cloud win"
      maxSize: 4
      maxTotalUses: -1
      minSize: 1
      minSpareSize: 0
      name: "code-cloud-win"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "eu-west-1"
      restrictUsage: true
      scaleExecutorsByWeight: false
``

**Anything else unique about your setup?**
Nope

**Comment by jhosemar-caylent** [comment]
Having a similar issue with an amazon linux 2. They main difference in my setup is that credentials are not required since i'm using an instance role, however i've noticed that when i'm submitting JCasC for this plugin my jenkins service timesout.

`Job for jenkins.service failed because a timeout was exceeded. See "systemctl status jenkins.service" and "journalctl -xe" for details.`

Current JCasC config 

```
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: true
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "jenkins/workers-keypair" # This is the name of the ssh key secret configured from secret manager
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy" 
      disableTaskResubmit: false
      fleet: "jenkins-worker-asg" # This is the name of the ASG that was created with the jenkins module
      idleMinutes: 30  # How long should the worker node stay idle before scaling down to 0
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "worker-nodes" # This is the label id for the jenkins jobs
      maxSize: 1
      maxTotalUses: -1
      minSize: 1
      name: "jenkins-worker-nodes" # This is the name of the cloud
      noDelayProvision: false
      numExecutors: 3
      privateIpUsed: true
      region: "us-east-1"
      restrictUsage: false
      scaleExecutorsByWeight: false
```

Jenkins version: [Jenkins 2.346](https://www.jenkins.io/)
Plugin Version: 2.5.1
