### ISSUE TITLE
Not able to create multiple clouds

### ISSUE THREAD

**Issue by hsmade** [jenkinsci/ec2-fleet-plugin#338]
## Issue Details

**Describe the bug**
Whenever I define multiple clouds, only the last one is active / creating agents. The other ones seem to not exist.
What I see in the controller log, is this:
```
Reassigned com.amazon.jenkins.ec2fleet.EC2FleetNode[i-xxxxxxxx] from first-fleet to second-fleet
```
Which obviously breaks this agent, as the two fleets are in different cloud accounts. So it doesn't exist in the `second-fleet` configuration.

**To Reproduce**
1. create and configure a working fleet on an AWS cloud account
2. notice the agents being registered and running in the overview (`/computer`)
3. create and configure a second fleet on another AWS cloud account
4. notice that only the agents of the second fleet are present in the overview (`/computer`)

## Environment Details

**Plugin Version?**
2.5.1

**Jenkins Version?**
2.319.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
``
Paste only eC2Fleet part from plugin configuration. Mask all security concerning details. You can download it from Manage Jenkins > Configuration as Code > Download Configuration
``
```yaml
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      awsCredentialsId: "first-fleet-aws"
      cloudStatusIntervalSec: 60
      computerConnector:
        sSHConnector:
          credentialsId: "first-fleet-ssh"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "jenkins-deploy"
      fsRoot: "/var/lib/jenkins"
      idleMinutes: 0
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "first-fleet"
      maxSize: 6
      maxTotalUses: -1
      minSize: 3
      minSpareSize: 0
      name: "first-fleet"
      noDelayProvision: false
      numExecutors: 10
      oldId: "xxxxxxxxxxx"
      privateIpUsed: true
      region: "eu-west-3"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      awsCredentialsId: "second-fleet-aws"
      cloudStatusIntervalSec: 60
      computerConnector:
        sSHConnector:
          credentialsId: "second-fleet-ssh"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "jenkins-deploy"
      fsRoot: "/var/lib/jenkins"
      idleMinutes: 0
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "second-fleet"
      maxSize: 6
      maxTotalUses: -1
      minSize: 3
      minSpareSize: 0
      name: "second-fleet"
      noDelayProvision: false
      numExecutors: 10
      oldId: "yyyyyyyyy"
      privateIpUsed: true
      region: "eu-west-3"
      restrictUsage: true
      scaleExecutorsByWeight: false

```

**Anything else unique about your setup?**
No
