### ISSUE TITLE
CloudNanny doRun - java.lang.NullPointerException - after reload of config

### ISSUE THREAD

**Issue by icep87** [jenkinsci/ec2-fleet-plugin#374]
## Issue Details

**Describe the bug**
Following error after reloading of configuration. 

```
        Jun 16, 2023 6:19:49 AM INFO com.amazon.jenkins.ec2fleet.CloudNanny doRun
        Error during fleet 'aws_ec2_spot_fleet' stats update
        java.lang.NullPointerException

```
To get it started again you have to visit Configure Clouds in Jenkins UI and save the settings once again.

**To Reproduce**
1. Reload "Configuration as Code" 
2. Check Jenkins logs.

## Environment Details

**Plugin Version?**
2.6.0

**Jenkins Version?**
2.387.1

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Config**

```
  clouds:
    - ec2fleet:
        name: aws_ec2_spot_fleet
        computerConnector:
          sshConnector:
            credentialsId: aws_ec2_spot_fleet
            sshHostKeyVerificationStrategy: NonVerifyingKeyVerificationStrategy
        fleet: "devops-jenkins-db-tools-linux-spot-agent"
        region: "eu-central-1"
        maxSize: 12
        privateIpUsed: true
        idleMinutes: 5
        numExecutors: 1

```
