### ISSUE TITLE
Validate cloud for JCasC

### ISSUE THREAD

**Issue by pdk27** [jenkinsci/ec2-fleet-plugin#393]
Today, validation exists only for UI users, configuring a cloud via _/configureClouds_. 
This issue is to track the effort for adding validations for cloud configured via JCasC.

**Comment by vineeth-bandi** [comment]
When clouds are defined list-style in CasC as below, they are passed in one at a time. This means we can't validate the config or its inputs directly in the plugin.

When managing Cloud Names currently, we query Jenkins which returns the current list of clouds. However, when any config changes are made to clouds, Jenkins prompts the plugins constructor to recreate all instances, but doesn't discriminate between new clouds and clouds that have config changes until [version 2.403](https://github.com/jenkinsci/jenkins/blob/jenkins-2.403/core/src/main/java/hudson/slaves/Cloud.java#L317-L335). This means validation would have to successfully discriminate these changes which after investigation seems infeasible. Since the state of Jenkins Cloud list and consecutive calls to the constructor cannot discriminate between these changes, we never receive an accurate state of the cloud before and after making warnings or automated fixes for duplicate cloud names nonviable through the plugin. Newer versions of Jenkins will automatically prevent names from being reused for clouds.

Another problem is that clouds don't seem to be created consecutively and instead functionally batched and then created by Jenkins. Given two clouds with identical names, the plugins constructor cannot create a cloud and see the updated cloud in Jenkins if a list of clouds was defined as Jenkins does not update its cloud list until all Clouds have been constructed. This prevents a scenario where the first cloud can be given the defined name and during the construction of the second cloud have its name altered by verifying it against the list of current clouds in Jenkins.

```
clouds:
    - eC2Fleet:
        computerConnector:
          sSHConnector:
            credentialsId: "aws-keypair"
            sshHostKeyVerificationStrategy: "NonVerifyingKeyVerificationStrategy"
        fleet: "ec2-asg"
        labelString: "ec2-fleet"
        name: "cloud-1"
        region: "us-east-2"
    - eC2Fleet:
        computerConnector:
          sSHConnector:
            credentialsId: "aws-keypair"
            sshHostKeyVerificationStrategy: "NonVerifyingKeyVerificationStrategy"
        fleet: "ec2-asg"
        labelString: "ec2-fleet"
        name: "cloud-2"
        region: "us-east-2"
```
