### ISSUE TITLE
Plugin doesn't scale nodes

### ISSUE THREAD

**Issue by kkurzyna** [jenkinsci/ec2-fleet-plugin#43]
Hi,

I have noticed, that scaling isn't working correctly. 

Case 1: There are few builds in queue
Plugin: Doesn't create new nodes and doesn't send to AWS request to increase fleet capacity (even thought spawning them wouldn't exceed max-cluster-size);

Case 2: Min cluster size is greater than 1
Plugin: Again, it will only create 1 node and will not spawn more.

Case 3: AWS spot fleet size is 2 and min cluster size is 2
Plugin: After some time Plugin will set AWS spot fleet capacity to 1, but will keep min cluster size at 2

The weirdest part is, those are some recent bugs - I have used this plugin for some time and I haven't notice such an issues earlier.

If someone knows, what is going on - answer please (or just bugifx it, if it really is a problem with plugin).

**Comment by daniilyar** [comment]
All the above reproduces for us also. Didn't find the line of code that actually scales fleet up from 0 to 1 so probably it is simply not implemented..

**Comment by michaljrk** [comment]
I can confirm the same happens for me, (I queued 5-6 execution of the same job, assigned to the fleet agents only and no scale out happened, the jobs just remained waiting). 

It would much appreciate to get any update on that issue.

**Comment by akennealy** [comment]
I can also reproduce it... builds in Queue but no fleet nodes spinning up to take on the job. 

Jenkins 150.1
eC2 fleet plugin 1.1.8

**Comment by vliubko** [comment]
Same situation.

Logs shows nothing, when I change minimal number of nodes
Also, when I manually set capacity of a Fleet to 0, plugin didn't do anything.

Only repeatable status check without any action
```
Jan 15, 2019 9:37:53 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Fleet Update Status called
Jan 15, 2019 9:37:53 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
# of nodes:1
Jan 15, 2019 9:37:53 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Fleet (ec2-fleet) contains instances [i-052bc465b309c8c8a]
Jan 15, 2019 9:37:53 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins contains dying instances []
Jan 15, 2019 9:38:03 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Fleet Update Status called
Jan 15, 2019 9:38:03 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
# of nodes:1
Jan 15, 2019 9:38:03 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Fleet (ec2-fleet) contains instances [i-052bc465b309c8c8a]
Jan 15, 2019 9:38:03 AM FINE com.amazon.jenkins.ec2fleet.EC2FleetCloud
Jenkins contains dying instances []
```

**Comment by andrea-vaccaro** [comment]
Hi,
we have replicated the problem with Jenkins 2.150.1 and EC2 Fleet plug-in 1.1.9: after the fleet is scaled down because of idle instances, new instances are not added to the fleet when needed, even though the number of existing instances is less then max cluster size.

@Plugin developers
Have you analyzed the problem?
Do you know if it possible to use a workaround?

We could disable the scaling mechanism but keeping the spot instances always running will cost too much.

Thanks,
Andrea

**Comment by bertjwregeer** [comment]
I am running the latest version of the plugin, with min cluster size: 1, and max cluster size: 5.

And scaling up/down works without issues.

**Comment by akennealy** [comment]
Same here, but this is a workaround for me -- I want to be able to set min to 0 so I'm not paying for 24/7 (spot) instances. I have to set it to 1 or else it wont scale up as one job comes into the queue.

**Comment by YOO629** [comment]
jenkins v2.138.2, ec2-spot-fleet-plugin v1.1.9, no issues here. scales up or down as expected. I haven't tried setting min cluster size to 0 since I want to keep a certain number of instances ready to go (scaling up tends to take quite a bit of time)

**Comment by chopmann** [comment]
I added Full-ec2 to the instance running the jenkins-master and created a FleetRequest with '0' as Target through cloudformation. Don't know which of the things solved my Issue (I think giving the full-ec2 to the master did it). Now plugin connects and behaves as expected.

**Comment by ianfixes** [comment]
Should I add any of this info to my documentation patch? https://github.com/jenkinsci/ec2-fleet-plugin/pull/56

**Comment by ebalakumar** [comment]
> jenkins v2.138.2, ec2-spot-fleet-plugin v1.1.9, no issues here. scales up or down as expected. I haven't tried setting min cluster size to 0 since I want to keep a certain number of instances ready to go (scaling up tends to take quite a bit of time)

I am using the same version . Setting min  cluster size to 0 is not downsizzing the instance

**Comment by rnhurt** [comment]
I'm experiencing this same problem.  My spot slave scales up/down just fine when the MIN instance is > 0.  Setting it to 0 causes the spot slave to terminate (after the idle timeout).  

When I run another job with that label, the job pauses (like it should) and reports that there are no instances with that label (like it should).  I've waited for 2 hours for the spot slave to startup but it never did.  Once I updated the MIN instance to 1 the spot slave started and the job ran.

**Comment by chopmann** [comment]
Probably to "wide" but this got my setup working:
![jenkins_conf](https://user-images.githubusercontent.com/2122863/56347252-2bedcd80-61c4-11e9-81ae-2305a87f0401.png)


```yaml
Resources:
  Ec2Role: # For Jenkins-Master
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'Ec2Role-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: SpotAgentPolicy
          # Policy is documented at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-iam-users
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
              - ec2:*
              - iam:ListInstanceProfiles
              - iam:ListRoles
              - iam:PassRole
              Resource: "*"

  IAMUserJenkins:
    Type: AWS::IAM::User
    Properties:
      UserName: XXXXX #  jenkins-fleet-user
      Policies:
      - PolicyName: SpotAgentPolicy
        # Policy is documented at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-iam-users
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - ec2:*
            - iam:ListInstanceProfiles
            - iam:ListRoles
            - iam:PassRole
            Resource: "*"

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: "jenkins-slave-small"
      LaunchTemplateData:
        # CreditSpecification: # needed for t2-t3
        #   CpuCredits: standard
        ImageId: "ami-XXXXXXX" # ci-jenkins-slave-base (ubuntu)
        InstanceType: "m3.medium"
        InstanceMarketOptions:
          SpotOptions:
            MaxPrice: "0.015"
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Arn: !ImportValue 'jenkins-security-SlaveProfile'
        NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          Groups:
            - !ImportValue 'jenkins-security-SlaveSG'
          DeleteOnTermination: true

  spotFleet:
    DependsOn:
      - LaunchTemplate
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        ExcessCapacityTerminationPolicy: Default
        AllocationStrategy: lowestPrice
        IamFleetRole: !ImportValue 'jenkins-security-SlaveRole'
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version:
                Fn::GetAtt:
                  [ "LaunchTemplate", "LatestVersionNumber" ]
            Overrides:
              - SubnetId: 
                  Fn::ImportValue: !Sub '${ParentVpcStack}-PublicAId'
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref LaunchTemplate
              Version:
                Fn::GetAtt:
                  [ "LaunchTemplate", "LatestVersionNumber" ]
            Overrides:
              - SubnetId: 
                  Fn::ImportValue: !Sub '${ParentVpcStack}-PublicBId'
        TargetCapacity: 0
        TerminateInstancesWithExpiration: true
```
