### ISSUE TITLE
Not detecting need to scale out

### ISSUE THREAD

**Issue by BradyShober** [jenkinsci/ec2-fleet-plugin#456]
## Issue Details

**Describe the bug**
We have observed instances where there are jobs in the queue that are waiting for an agent that does not seem to be triggering the plugin to adjust the desired count on the Auto Scaling Group. In the logs, we see entries such as `label [linux-small]: No excess workload, provisioning not needed.`
When this log was observed, there were 8 items in the queue waiting for an agent with that label. The desired count of the ASG at the time was set to 2, then dropped to 1, our maximum for this is 50. If I manually adjust the count agents will launch and jobs will be processed. I have seen the count at 0 while there were items in the queue for several hours earlier today.

**To Reproduce**
It is unclear what exactly leads to this state, however I would say we see issues like this more often when there is a lot of build activity occurring.

** Logs **
```
Mar 08, 2025 3:58:00 AM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
label [linux-small]: No excess workload, provisioning not needed.
```

## Environment Details

**Plugin Version?**
3.0.2

**Jenkins Version?**
2.479.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
```
clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "linuxasg-small-v1"
      fsRoot: "/home/jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 300
      labelString: "linux-small"
      maxSize: 50
      maxTotalUses: 1
      minSize: 0
      minSpareSize: 0
      name: "Linux ASG - Small"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "linuxasg-medium-v1"
      fsRoot: "/home/jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 300
      labelString: "linux-medium"
      maxSize: 20
      maxTotalUses: 1
      minSize: 0
      minSpareSize: 0
      name: "Linux ASG - Medium"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "linuxasg-large-v1"
      fsRoot: "/home/jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 300
      labelString: "linux-large"
      maxSize: 15
      maxTotalUses: 1
      minSize: 0
      minSpareSize: 0
      name: "Linux ASG - Large"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "linuxasg-xlarge-v1"
      fsRoot: "/home/jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 300
      labelString: "linux-xlarge"
      maxSize: 10
      maxTotalUses: 1
      minSize: 0
      minSpareSize: 0
      name: "Linux ASG - XL"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "linuxasg-guidewire-v1"
      fsRoot: "/home/jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 300
      labelString: "linux-guidewire"
      maxSize: 10
      maxTotalUses: 1
      minSize: 0
      minSpareSize: 0
      name: "Linux ASG - Guidewire"
      noDelayProvision: true
      numExecutors: 1
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "windowsasg-small-v1"
      fsRoot: "D:\\Jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "windows-small"
      maxSize: 20
      maxTotalUses: 10
      minSize: 5
      minSpareSize: 2
      name: "Windows ASG - Small"
      noDelayProvision: true
      numExecutors: 4
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "windowsasg-medium-v1"
      fsRoot: "D:\\Jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "windows-medium"
      maxSize: 20
      maxTotalUses: 10
      minSize: 0
      minSpareSize: 0
      name: "Windows ASG - Medium"
      noDelayProvision: true
      numExecutors: 4
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "windowsasg-large-v1"
      fsRoot: "D:\\Jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "windows-large"
      maxSize: 15
      maxTotalUses: 10
      minSize: 0
      minSpareSize: 0
      name: "Windows ASG - Large"
      noDelayProvision: true
      numExecutors: 4
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "EC2_FLEET_ASG"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          prefixStartSlaveCmd: ""
          retryWaitTime: 15
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      disableTaskResubmit: false
      fleet: "windowsasg-xlarge-v1"
      fsRoot: "D:\\Jenkins"
      idleMinutes: 120
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 600
      labelString: "windows-xlarge"
      maxSize: 5
      maxTotalUses: 10
      minSize: 0
      minSpareSize: 0
      name: "Windows ASG - XL"
      noDelayProvision: true
      numExecutors: 4
      privateIpUsed: true
      region: "us-east-2"
      restrictUsage: true
      scaleExecutorsByWeight: false
```

**Anything else unique about your setup?**
No
